import type { Project } from './projects';

export const builds: Project[] = [
  {
    slug: 'citizen-sir-watch', category: 'independent', publication: 'listed',
    company: 'Citizen SIR Watch',
    title: 'Citizen SIR Watch', descriptor: 'Finding public notices by Voter ID.',
    role: 'Independent project · Product development',
    format: 'Independent web tool. Limited Karnataka coverage; not an official government service.',
    themes: ['Public-data access', 'Source provenance', 'Bilingual interface'],
    summary: 'An independent search tool for the official notice records currently indexed, with links to the original sources.',
    outcomes: [],
    repository: { href: 'https://github.com/soniparneet/citizen-sir-watch', label: 'View code on GitHub' },
    liveUrl: 'https://citizen-sir-watch.vercel.app/',
    sections: [
      { id: 'problem', title: 'The problem: finding the relevant notice', body: 'Official notice records are spread across documents. I built Citizen SIR Watch to make the indexed records searchable by one EPIC / Voter ID, without asking people to choose a constituency or workflow stage first.' },
      { id: 'built', title: 'What I built', body: 'The search checks the live indexed datasets and links matches to their official sources. English and Kannada interface text supports navigation, while names, reasons, and other source values stay exactly as published.' },
      { id: 'choices', title: 'Important choices in the product', body: 'A simple entry point still needs clear boundaries. Coverage is visible, and results retain a route back to the source document. A no-match message explains what the search can - and cannot - establish.\n\nValid rows can be searched even when other rows in the same document fail validation. Malformed values are excluded, not repaired by guessing.\n\nSearch uses POST requests to keep identifiers out of normal search URLs. The application does not intentionally store search history in its database; this is not a guarantee of complete anonymity.' },
      { id: 'implementation', title: 'From public documents to a source-linked result', body: 'Public documents → validated records → searchable index → source-linked result.\n\nPython ingestion handles public notice files separately from the website. Accepted records and source references are stored in PostgreSQL; the Next.js app performs a server-side, parameterized identifier lookup. Search includes accepted records from fully and partially processed documents.' },
      { id: 'limits', title: 'Current capability and limits', body: 'Citizen SIR Watch is independent, not an official government service. Coverage is limited to specified Karnataka constituencies, not the whole state; the live product lists the datasets currently indexed.\n\nA no-match result does not establish voting eligibility, the absence of a notice, or complete electoral status. Official election sources remain authoritative. Search is a way to find a source record, not an electoral-status determination.' },
    ],
    cover: { id: 'citizen-public-entry', title: 'Citizen SIR Watch · Search entry', src: '/projects/citizen-sir-watch/public-search-entry.png', width: 1440, height: 656, alt: 'Citizen SIR Watch public search entry with an empty Voter ID input and notice guidance.', previewCaption: 'Independent tool, not an official government service.', caption: 'Citizen SIR Watch’s empty search entry. Independent service with limited Karnataka coverage. Captured 13 September 2026.', order: 1, provenance: 'original' }, gallery: [],
    prototype: { status: 'planned' },
  },
  {
    slug: 'product-sense-practice', category: 'independent', publication: 'listed',
    company: 'AI Skill: PM Interviewer',
    title: 'AI Skill: PM Interviewer', descriptor: 'AI-guided product interview practice.',
    role: 'Independent project · Framework adaptation, interaction design & iteration',
    format: 'AI instruction workflow. Framework: Ben Erez / Lenny’s Newsletter.',
    homepageExcerpt: {
      text: 'I’ll broadly consider adults around retirement age and above, but I won’t treat age itself as the segmentation axis. Older investors can differ substantially in financial literacy, income sources, goals, digital confidence, and dependence on family.',
      context: 'User scope · Hypothetical Zerodha Coin exercise · Excerpt',
      attribution: 'Owner-provided response. Framework foundation: Ben Erez / Lenny’s Newsletter.',
      limitation: 'No Zerodha affiliation or hosted chatbot.',
    },
    themes: ['AI learning workflow', 'Interaction design', 'Qualitative evaluation'],
    summary: 'AI skill for practising PM interviews with structured prompts, examples, and coaching.',
    outcomes: [],
    repository: { href: 'https://github.com/soniparneet/product-sense-practice', label: 'View project on GitHub' },
    exampleUrl: 'https://github.com/soniparneet/product-sense-practice/blob/main/examples/candidate-example.md',
    sections: [
      { id: 'problem', title: 'The problem: an answer is not a learning experience', body: 'A polished Product Sense answer can show the destination without making the reasoning reusable. I adapted a framework into staged practice: choosing a user, prioritizing a problem, comparing solutions, and explaining the decisions that connect them.' },
      { id: 'built', title: 'What I built', body: 'I adapted the credited framework into reusable instructions, designed the interaction, refined the rules, and documented setup and limitations. It runs as an instruction-based experience inside ChatGPT, not as a separately hosted application or a trained model.\n\nIn Candidate mode, the AI demonstrates an answer one stage at a time. In Instructor mode, the person answers while the AI interviews and coaches. Stage checkpoints and pacing estimates keep the flow bounded. Visible decisions, separate coaching cues, and reusable patterns expose the method alongside the answer.' },
      { id: 'choices', title: 'The decision: teach the method, not just the answer', body: 'A reasoning-focused revision produced polished answers but made the method harder to learn. I separated natural Candidate speech from compact coaching marked “not spoken,” and treated answer quality and learning quality as different goals.\n\nSegmentation also required reversals. A single dominant axis made categories consistent but sometimes hid combinations that changed the need. A later peer-archetype rule could still become too rigid. The current instructions favor recognizable, need-based groups whose differences could change the product decision, without allowing arbitrary combinations. ' },
      { id: 'example', title: 'An example of the teaching layer', body: 'The public Candidate example frames a product for people moving to a new city, then pauses after the first stage. Its separate coaching layer names the purpose of that stage. This is a newly written public-safe illustration, not a benchmark transcript or a live demo.', excerpt: { text: 'Define the playing field without prematurely choosing the user, problem, or solution.', label: 'AI Skill: PM Interviewer · Candidate example · 13 September 2026', href: 'https://github.com/soniparneet/product-sense-practice/blob/main/examples/candidate-example.md' } },
      { id: 'evidence', title: 'What the evaluation does - and does not - show', body: 'I used qualitative, model-assisted review of generated Candidate answers and synthetic Instructor cases to refine the instructions. Most retained runs were single samples, and development prompts were reused. There is no independent human learning study or retained full-suite rerun for the exact public release. These checks do not establish measured learning or hiring gains.' },
      { id: 'credits', title: 'Foundation, attribution, and next learning', body: 'Ben Erez’s framework, published by Lenny’s Newsletter, provides the foundation. My work is the adaptation and iteration, with ChatGPT and Codex assistance for drafting, critique, instruction revision, testing support, and repository implementation. I do not claim to have invented the underlying methodology.\n\nThis is an independent project, not an official or endorsed Stripe or OpenAI product. No reuse license has been selected. Fresh prompts, repeated trials, and blinded human review would be useful next steps. Model behavior varies, and employer-specific calibration remains unestablished.' },
    ],
    cover: {
      id: 'practice-assumptions', title: 'AI Skill: PM Interviewer · Assumptions example',
      src: '/projects/product-sense-practice/assumptions-full.webp', width: 1610, height: 900,
      preview: { src: '/projects/product-sense-practice/assumptions-full.webp', width: 1610, height: 900 },
      alt: 'AI Skill: PM Interviewer response: Stage 0 introduces a hypothetical Zerodha Coin prompt and lists role, geography, user-scope and constraint assumptions.',
      previewCaption: 'Detail crop: a hypothetical Zerodha Coin interview answer. No employer affiliation.',
      caption: 'An instruction-based practice response to a hypothetical Zerodha Coin prompt. This crop retains the complete assumptions section; application chrome and the cut-off next section are omitted. It is not a claim of employment at Zerodha or a hosted portfolio chatbot.',
      presentation: 'document', order: 1, provenance: 'owner-provided example',
    },
    gallery: [], prototype: { status: 'planned' },
  },
];
